import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossOrigin="anonymous"/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="row ">
          <div className="col-3 m-2 border border-danger ">
              logo here
          </div>
          <div className="col m-2 border border-danger ">
              menu here
          </div>
        </div>
        <div className="row ">
          <div className="col-4 m-2 border border-danger ">
              Side bar here
          </div>
          <div className="col m-2 border border-danger ">
              {children}
          </div>
        </div>
        <div className="row ">
          <div className="col m-2 text-center border border-danger ">
              footer
          </div>
        </div>
      </body>
    </html>
  );
}
